FROM boyzwj1984/elixir-ubuntu-dev:v1

# ARG GIT_USER_NAME
# ARG SVN_USER_NAME
# ARG SVN_PASSWORD
# ENV GIT_USER_NAME=${GIT_USER_NAME}\
#     ERL_AFLAGS="-kernel shell_history enabled"\
#     SVN_USER_NAME=${SVN_USER_NAME}\
#     SVN_PASSWORD=${SVN_PASSWORD}

RUN git config --global --add safe.directory /ws/sorted_set_nif
WORKDIR /ws/m1x